OnlineTesting/Controllers/TestManagementController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Host;
using OnlineTesting.Data;
using OnlineTesting.Interfaces;
using OnlineTesting.Models;
using OnlineTesting.Models.TestViewModels;

namespace OnlineTesting.Controllers
{
    [Authorize]
    public class TestManagementController : BasicController
    {
        private readonly ITestManagementService _testManagementService;


        public TestManagementController(
            UserManager<ApplicationUser> userManager,
            ITestManagementService managementService
        ) : base(userManager)
        {
            _testManagementService = managementService;
        }


        public IActionResult Index()
        {
            var tests = _testManagementService.GetTests();
            return View(tests);
        }


        public async Task<IActionResult> Create()
        {
            var test = new TestVM();
            _testManagementService.SetCurrentCachedTest(test, await GetCurrentUser());
            return RedirectToAction("Save", new {id = test.Id});
        }


        public async Task<IActionResult> Edit(string id)
        {
            var test = _testManagementService.GetTestFromDataBase(id);
            if (test == null)
            {
                return NotFound();
            }
            _testManagementService.SetCurrentCachedTest(test, await GetCurrentUser());
            return RedirectToAction("Save", new {id});
        }


        public async Task<IActionResult> Save(string id)
        {
            var test = _testManagementService.GetCurrnentTest(id, await GetCurrentUser());
            return View("CreateEdit", test);
        }

        [HttpPost]
        public async Task<IActionResult> Save(TestVM test)
        {
            if (ModelState.IsValid)
            {
                _testManagementService.AddOrUpdateCachedTest(test, await GetCurrentUser());

                return RedirectToAction("Index", "Questions", new {testId = test.Id});
            }

            return View("CreateEdit", test);
        }


        public async Task<IActionResult> Submit(string testId)
        {
            if (_testManagementService.CheckCurrentTestIsValid(testId, await GetCurrentUser()))
            {
                if (_testManagementService.SaveCurrentTestToDatabase(testId, await GetCurrentUser()))
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Timeout", "Error");
            }

            return RedirectToAction("Index", "Questions", new {testId = testId, showErrors = true});
        }

        public IActionResult Delete(string id)
        {
            _testManagementService.DeactivateTest(id);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Cancel(string testId)
        {
            _testManagementService.CancelCurrentAction(testId, await GetCurrentUser());
            return RedirectToAction("Index");
        }
    }
}

OnlineTesting/Controllers/UserManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineTesting.Data;
using OnlineTesting.Interfaces;
using OnlineTesting.Models;
using OnlineTesting.Models.UserViewModels;

namespace OnlineTesting.Controllers
{
    public class UserManagementController : BasicController
    {
        private readonly IUserManagementService _userManagementService;

        public UserManagementController(IUserManagementService userManagementService, UserManager<ApplicationUser> userManager) : base(userManager)
        {
            _userManagementService = userManagementService;
        }

        public IActionResult Index()
        {
            return View(_userManagementService.GetUserList());
        }

        public IActionResult Edit(string id)
        {
            var user = _userManagementService.GetUser(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserVM user)
        {
            if (ModelState.IsValid)
            {
                var result = await _userManagementService.SaveUserEdit(user);
                return RedirectToAction("Index");
            }

            return View(user);
        }
    }
}

OnlineTesting/Views/Shared/_Layout.cshtml
@using OnlineTesting.Data
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - OnlineTesting</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>


    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css"/>

        <link rel="stylesheet" href="~/lib/datatables/media/css/dataTables.bootstrap.min.css" />


    </environment>

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">OnlineTesting</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Main"]</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Ratings">@Localizer["Ratings"]</a>
                </li>

                @if (User.Identity.IsAuthenticated)
                {
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Results">@Localizer["MyResults"]</a>
                    </li>
                }

                @* TODO fix hardcoded admin *@
                @if (User.Identity.IsAuthenticated &&
                     ((await UserManager.GetRolesAsync(
                         await UserManager.GetUserAsync(User)))?.Any(role => role == "admin") ?? false))
                {
                    <li>
                        <a asp-area="" asp-controller="TestManagement" asp-action="Index">@Localizer["TestManagement"]</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="UserManagement" asp-action="Index">@Localizer["UserManagement"]</a>
                    </li>
                }

            </ul>
            @await Html.PartialAsync("_LoginPartial")
        </div>
    </div>
</div>


<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/datatables/media/js/jquery.dataTables.js"></script>
    <script src="~/lib/datatables/media/js/dataTables.bootstrap.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>


<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    <script src="~/lib/datatables/media/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/media/js/dataTables.bootstrap.min.js"></script>

    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

<script src="~/lib/confirm-bootstrap/confirm-bootstrap.js"></script>

@RenderSection("scripts", false)


<div class="container body-content">
    <div style="margin-top: 4em">
        @RenderBody()
    </div>
    <footer style="position: fixed; bottom: 10px;">
        <p>&copy; 2017 - OnlineTesting</p>
    </footer>
</div>


</body>
</html>