OnlineTesting/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using OnlineTesting.Data;
using OnlineTesting.Interfaces;
using OnlineTesting.Models;
using OnlineTesting.Models.AnswersViewModels;
using OnlineTesting.Models.TestViewModels;

namespace OnlineTesting.Controllers
{
    public class AnswersController : BasicController
    {
        private readonly IAnswersService _answersService;

        public AnswersController(IAnswersService answersService,
            UserManager<ApplicationUser> userManager
        ) : base(userManager)
        {
            _answersService = answersService;
        }

        public async Task<IActionResult> Index(string testId, string questionId, bool? showErrors)
        {
            var answers =
                _answersService.GetAnswrsFor(testId, questionId, await GetCurrentUser());

            if (answers == null)
            {
                return RedirectToAction("Timeout", "Error");
            }

            if (showErrors ?? false)
            {
                var errors =
                    _answersService.GetModelStateErrors(testId, questionId, await GetCurrentUser());

                foreach (var error in errors)
                {
                    ModelState.AddModelError("", error);
                }
            }

            return View(new AnswersIndexVM() {QuestionId = questionId, Answers = answers, TestId = testId});
        }

        public IActionResult Create(string questionId, string testId)
        {
            var answer = new AnswerVM() {QuestionId = questionId, TestId = testId};
            return View("CreateEdit", answer);
        }

        [HttpPost]
        public async Task<IActionResult> Save(AnswerVM answer)
        {
            if (ModelState.IsValid)
            {
                _answersService.SaveAnswer(answer, await GetCurrentUser());
                return RedirectToAction("Index", new {questionId = answer.QuestionId, testId = answer.TestId});
            }

            return View("CreateEdit", answer);
        }

        public async Task<IActionResult> Edit(string id, string questionId, string testId)
        {
            var answer =
                _answersService.GetAnswer(id, questionId, testId, await GetCurrentUser());
            return View("CreateEdit", answer);
        }

        public async Task<IActionResult> Delete(string id, string questionid, string testId)
        {
            _answersService.RemoveAnswer(id, questionid, testId, await GetCurrentUser());

            return RedirectToAction("Index", new {questionId = questionid, testId});
        }

        public async Task<IActionResult> Submit(string questionId, string testId)
        {
            if (_answersService.CheckQuestionStateIsValid(questionId, testId, await GetCurrentUser())
            )
            {
                return RedirectToAction("Index", "Questions", new {testId});
            }
            return RedirectToAction("Index", new {questionId, testId, showErrors = true});
        }
    }
}

OnlineTesting/Controllers/TestManagementController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Host;
using OnlineTesting.Data;
using OnlineTesting.Interfaces;
using OnlineTesting.Models;
using OnlineTesting.Models.TestViewModels;

namespace OnlineTesting.Controllers
{
    [Authorize]
    public class TestManagementController : BasicController
    {
        private readonly ITestManagementService _testManagementService;


        public TestManagementController(
            UserManager<ApplicationUser> userManager,
            ITestManagementService managementService
        ) : base(userManager)
        {
            _testManagementService = managementService;
        }


        public IActionResult Index()
        {
            var tests = _testManagementService.GetTests();
            return View(tests);
        }


        public async Task<IActionResult> Create()
        {
            var test = new TestVM();
            _testManagementService.SetCurrentCachedTest(test, await GetCurrentUser());
            return RedirectToAction("Save", new {id = test.Id});
        }


        public async Task<IActionResult> Edit(string id)
        {
            var test = _testManagementService.GetTestFromDataBase(id);
            if (test == null)
            {
                return NotFound();
            }
            _testManagementService.SetCurrentCachedTest(test, await GetCurrentUser());
            return RedirectToAction("Save", new {id});
        }


        public async Task<IActionResult> Save(string id)
        {
            var test = _testManagementService.GetCurrnentTest(id, await GetCurrentUser());
            return View("CreateEdit", test);
        }

        [HttpPost]
        public async Task<IActionResult> Save(TestVM test)
        {
            if (ModelState.IsValid)
            {
                _testManagementService.AddOrUpdateCachedTest(test, await GetCurrentUser());

                return RedirectToAction("Index", "Questions", new {testId = test.Id});
            }

            return View("CreateEdit", test);
        }


        public async Task<IActionResult> Submit(string testId)
        {
            if (_testManagementService.CheckCurrentTestIsValid(testId, await GetCurrentUser()))
            {
                if (_testManagementService.SaveCurrentTestToDatabase(testId, await GetCurrentUser()))
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Timeout", "Error");
            }

            return RedirectToAction("Index", "Questions", new {testId = testId, showErrors = true});
        }

        public IActionResult Delete(string id)
        {
            _testManagementService.DeactivateTest(id);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Cancel(string testId)
        {
            _testManagementService.CancelCurrentAction(testId, await GetCurrentUser());
            return RedirectToAction("Index");
        }
    }
}

OnlineTesting/Views/Answers/CreateEdit.cshtml
@using OnlineTesting.Models.AnswersViewModels
@model AnswerVM

<form asp-action="Save">
    <div class="form-horizontal">
        <h4>AnswerVM</h4>
        <hr/>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input asp-for="QuestionId"/>
        <input asp-for="TestId"/>
        <input asp-for="Id"/>
        <input asp-for="IsActive"/>

        <div class="form-group">
            <label asp-for="Text" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Text" class="form-control"/>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <div class="checkbox">
                    <input asp-for="IsCorrect"/>
                    <label asp-for="IsCorrect"></label>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@SharedLocalizer["Submit"]" class="btn btn-primary"/>
                <a asp-action="Index"
                   asp-route-testId="@Model.TestId"
                   asp-route-questionId="@Model.QuestionId"
                   class="btn btn-default">
                    @SharedLocalizer["Back"]
                </a>
                <a class="btn btn-danger"
                   asp-action="Cancel"
                   asp-controller="TestManagement"
                   asp-route-testId="@Model.TestId">
                    @SharedLocalizer["Cancel"]
                </a>
            </div>
        </div>
    </div>
</form>

OnlineTesting/Views/Answers/Index.cshtml
@model OnlineTesting.Models.AnswersViewModels.AnswersIndexVM


<div asp-validation-summary="ModelOnly" class="text-danger"></div>


<p>
    <a asp-action="Create" asp-route-questionId="@Model.QuestionId" asp-route-testId="@Model.TestId">@SharedLocalizer["Create"]</a>
</p>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Answers.First().Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Answers.First().IsCorrect)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Answers)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsCorrect)
            </td>
            <td>
                <a
                    asp-action="Edit"
                    asp-controller="Answers"
                    asp-route-id="@item.Id"
                    asp-route-testId="@item.TestId"
                    asp-route-questionId="@item.QuestionId">
                    @SharedLocalizer["Edit"]
                </a> |
                <a asp-action="Delete"
                   asp-controller="Answers"
                   asp-route-id="@item.Id"
                   asp-route-testId="@item.TestId"
                   asp-route-questionId="@item.QuestionId"
                   class="delete">
                    @SharedLocalizer["Delete"]
                </a>

            </td>
        </tr>
    }
    </tbody>
</table>

<p>
    <a class="btn btn-primary"
       asp-action="Submit"
       asp-route-questionId="@Model.QuestionId"
       asp-route-testId="@Model.TestId">
        @SharedLocalizer["Submit"]
    </a>
    <a class="btn btn-default"
       asp-action="Edit"
       asp-controller="Questions"
       asp-route-id="@Model.QuestionId"
       asp-route-testId="@Model.TestId">
        @SharedLocalizer["Back"]
    </a>
    <a class="btn btn-danger"
       asp-action="Cancel"
       asp-controller="TestManagement"
       asp-route-testId="@Model.TestId">
        @SharedLocalizer["Cancel"]
    </a>

</p>