OnlineTesting/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using OnlineTesting.Data;
using OnlineTesting.Interfaces;
using OnlineTesting.Models.HomeViewModels;

namespace OnlineTesting.Controllers
{
    [Authorize]
    public class HomeController : BasicController
    {
        private readonly IHomeService _homeService;

        public HomeController(IHomeService homeService,
            UserManager<ApplicationUser> userManager
        ) : base(userManager)
        {
            _homeService = homeService;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            return View(new SearchVM() {Tests = _homeService.GetAvailableTests()});
        }

        [HttpPost]
        public IActionResult Index(SearchVM searchParams)
        {
            searchParams.Tests =
                _homeService.GetAvailableTests(searchParams.Name, searchParams.CategoryId, searchParams.Difficulty);
            return View(searchParams);
        }

        public IActionResult Start(string id)
        {
            return View(_homeService.GetTest(id));
        }

        public async Task<IActionResult> Results()
        {
            return View(_homeService.GetResultsFor(await GetCurrentUser()));
        }

        [AllowAnonymous]
        public IActionResult Ratings(string testId)
        {
            var ratings = _homeService.GetRatingsFor(testId);

            return View(new RatingsVM() {Ratings = ratings});
        }
    }
}

OnlineTesting/Controllers/TestingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineTesting.Data;
using OnlineTesting.Interfaces;
using OnlineTesting.Models;
using OnlineTesting.Models.AnswersViewModels;
using OnlineTesting.Models.TestingViewModels;

namespace OnlineTesting.Controllers
{
    public class TestingController : BasicController
    {
        private readonly ITestingService _testingService;

        public TestingController(
            ITestingService testingService,
            UserManager<ApplicationUser> userManager
        ) : base(userManager)
        {
            _testingService = testingService;
        }


        [HttpPost]
        public async Task<IActionResult> Start(string id, bool isRated)
        {
            var resultId = _testingService.PrepareForTesting(id, isRated, await GetCurrentUser());
            return RedirectToAction("Next", new {resultId});
        }

        public async Task<IActionResult> Next(string resultId)
        {
            var question = _testingService.GetNextQuestion(await GetCurrentUser());

            if (question == null)
            {
                return RedirectToAction("Result", new {resultId});
            }

            return View(new NextVM() {Question = question, ResultId = resultId});
        }

        [HttpPost]
        public async Task<IActionResult> Next(List<String> Checked, string questionId, string resultId)
        {
            _testingService.AddAnswerResult(Checked, questionId, resultId, await GetCurrentUser());
            return RedirectToAction("Next", new {resultId});
        }

        public async Task<IActionResult> Result(string resultId)
        {
            var result = _testingService.GetResult(resultId ,await GetCurrentUser());
            if (result == null)
            {
                return RedirectToAction("Timeout", "Error");
            }
            return View(result);
        }
    }
}

OnlineTesting/Views/Home/Index.cshtml
@using OnlineTesting.Interfaces
@model OnlineTesting.Models.HomeViewModels.SearchVM
@inject ITestManagementService TestManagementService
<style>
    
    .search-form {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        flex-wrap: wrap;
    }
    
</style>

<form asp-controller="Home" asp-action="Index" method="post" class="search-form">

    <div class="form-group  col-xs-4 col-md-4">
        <label asp-for="Name" class=" control-label"></label>
            <input asp-for="Name" class="form-control"/>
    </div>

    <div class="form-group col-xs-4 col-md-4">
        <label asp-for="CategoryId" class=" control-label"></label>
        @Html.DropDownListFor(vm => vm.CategoryId, TestManagementService.GetSelectableCategories(),"", new {@class = "form-control"})
    </div>
    
    <div class="form-group  col-xs-4 col-md-4">
        <label asp-for="Difficulty" class=" control-label"></label>
            @Html.DropDownListFor(vm => vm.Difficulty, new SelectList(Enumerable.Range(1, 10)),"", new {@class = "form-control"})
    </div>

    <div style="margin-left: 15px">
        <button type="submit" class="btn btn-default">@SharedLocalizer["Filter"]</button>
    </div>

</form>


<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tests.First().Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tests.First().CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tests.First().Difficulty)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Tests)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Difficulty)
            </td>
            <td>
                <a asp-action="Start" asp-controller="Home" asp-route-id="@item.Id">
                    @SharedLocalizer["Start"]
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

OnlineTesting/Views/Home/Ratings.cshtml
@using OnlineTesting.Interfaces
@model OnlineTesting.Models.HomeViewModels.RatingsVM

@inject ITestManagementService TestManagementService

<form asp-controller="Home" asp-action="Ratings" method="Get" class="search-form">

    <div class="form-group col-xs-12 ">
        <label asp-for="TestId" class=" control-label"></label>
        @Html.DropDownListFor(vm => vm.TestId,
            TestManagementService.GetTests().Select(vm => new SelectListItem() {Text = vm.Name, Value = vm.Id}),
            "",
            new {@class = "form-control"}
        )
    </div>
    <div style="margin-left: 15px">
        <button type="submit" class="btn btn-default">@SharedLocalizer["Filter"]</button>
    </div>

</form>


<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ratings.First().User.Username)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Ratings.First().Score)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Ratings)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
        </tr>
    }
    </tbody>
</table>

OnlineTesting/Views/Home/Results.cshtml
@model IEnumerable<OnlineTesting.Models.TestingViewModels.TestResultVM>


<table class="table" id="results-table">
    <thead>
        <tr>

            <th>
                    @Html.DisplayNameFor(model => model.TestId)
                </th>
            <th>
                @Html.DisplayNameFor(model => model.Test.CategoryId)
            </th>

            <th>
                    @Html.DisplayNameFor(model => model.DatePassed)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AccumulatedScore)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MaxScore)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsRated)
                </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Test.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Test.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DatePassed)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AccumulatedScore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxScore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsRated)
            </td>
        </tr>
}
    </tbody>
</table>

<script>
    $('#results-table').dataTable({
        'language': site.DataTableLanguage
    });
    
</script>

OnlineTesting/Views/Home/Start.cshtml
@model OnlineTesting.Models.TestViewModels.TestVM

@inject IViewLocalizer Localizer

<div>
    <h4>TestVM</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Difficulty)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Difficulty)
        </dd>
    </dl>
</div>
<div>
    <form asp-controller="Testing" asp-action="Start" method="post" class="form-horizontal">

            <input asp-for="Id"/>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <div class="checkbox">
                        <input type="checkbox"  id="isRated" name="isRated" value="true"/>
                        <label for="isRated">@Localizer["isRated"]</label>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">@SharedLocalizer["Start"]</button>
                </div>
            </div>

    </form>
</div>

<a asp-action="Index">@SharedLocalizer["Back"]</a>