OnlineTesting/Controllers/QuestionsController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineTesting.Data;
using OnlineTesting.Interfaces;
using OnlineTesting.Models;
using OnlineTesting.Models.QuestionViewModels;
using OnlineTesting.Models.TestViewModels;
using Remotion.Linq.Clauses.ResultOperators;

namespace OnlineTesting.Controllers
{
    public class QuestionsController : BasicController
    {
        private readonly IQuestionsService _questionsService;

        public QuestionsController(
            UserManager<ApplicationUser> userManager,
            IQuestionsService questionsService
        ) : base(userManager)
        {
            _questionsService = questionsService;
        }


        public async Task<IActionResult> Index(string testId, bool? showErrors)
        {
            var questions =
                _questionsService.GetCurrnentQuestions(testId, await GetCurrentUser());
            if (questions == null)
            {
                return RedirectToAction("Timeout", "Error");
            }

            if (showErrors ?? false)
            {
                var errors =
                    _questionsService.GetQuestionErrors(testId, await GetCurrentUser());
                foreach (var error in errors)
                {
                    ModelState.AddModelError(error.MemberNames.FirstOrDefault() ?? "", error.ErrorMessage);
                }
            }

            return View(new QuestionsIndexVM() {Questions = questions, TestId = testId});
        }


        public IActionResult Create(string testId)
        {
            return View("CreateEdit", new QuestionVM() {TestId = testId});
        }

        [HttpPost]
        public async Task<IActionResult> Save(QuestionVM question)
        {
            if (ModelState.IsValid)
            {
                if (_questionsService.AddOrUpdateQuestionOfCurrentTest(question, await GetCurrentUser()))
                {
                    return RedirectToAction("Index", "Answers",
                        new {questionId = question.Id, testId = question.TestId});
                }
                return RedirectToAction("Timeout", "Error");
            }
            return View("CreateEdit", question);
        }

        public async Task<IActionResult> Delete(string id, string testId)
        {
            _questionsService.RemoveQuestion(testId, id, await GetCurrentUser());
            return RedirectToAction("Index", new {testId});
        }

        public async Task<IActionResult> Edit(string id, string testId)
        {
            var question = _questionsService.GetQuestion(testId, id, await GetCurrentUser());
            if (question == null)
            {
                return RedirectToAction("Timeout", "Error");
            }
            return View("CreateEdit", question);
        }

        public async Task<IActionResult> Submit(string testId)
        {
            if (_questionsService.CheckQuestionsAreValid(testId, await GetCurrentUser()))
            {
                return RedirectToAction("Submit", "TestManagement", new {testId});
            }

            return RedirectToAction("Index", new {testId, showErrors = true});
        }
    }
}

OnlineTesting/Views/Questions/CreateEdit.cshtml
@using OnlineTesting.Models.QuestionViewModels
@model OnlineTesting.Models.QuestionViewModels.QuestionVM

<form asp-action="Save">
    <div class="form-horizontal">
        <h4>QuestionVM</h4>
        <hr/>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <input asp-for="Id"/>
        <input asp-for="TestId"/>
        <input asp-for="IsActive"/>

        <div class="form-group">
            <label asp-for="Time" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Time" class="form-control"/>
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Score" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                @Html.DropDownListFor(
                    model => model.Score,
                    new SelectList(Enumerable.Range(1, 5)),
                    new {@class = "form-control"}
                    )
                <span asp-validation-for="Score" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Text" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Text" class="form-control"/>
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="@SharedLocalizer["Next"]" class="btn btn-primary"/>
                <a asp-action="Index"
                   asp-route-testId="@Model.TestId"
                   class="btn btn-default">
                    @SharedLocalizer["Back"]
                </a>
                <a class="btn btn-danger"
                   asp-action="Cancel"
                   asp-controller="TestManagement"
                   asp-route-testId="@Model.TestId">
                    @SharedLocalizer["Cancel"]
                </a>

            </div>
        </div>

    </div>
</form>

OnlineTesting/Views/Questions/Index.cshtml
@using OnlineTesting.Models.QuestionViewModels
@model QuestionsIndexVM


<div asp-validation-summary="ModelOnly" class="text-danger"></div>


<p>
    <a asp-action="Create" asp-route-testId="@Model.TestId">@SharedLocalizer["Create"]</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().Time)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().Score)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Questions.First().Text)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Questions)
    {
        <tr
            @if (ViewData.ModelState.ContainsKey(item.Id))
            {
                <text>
                    class="alert alert-danger"
                </text>
            }
        >
            <td>
                @Html.DisplayFor(modelItem => item.Time)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Score)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                <a asp-action="Edit"
                   asp-controller="Questions"
                   asp-route-id="@item.Id"
                   asp-route-testId="@item.TestId">
                    @SharedLocalizer["Edit"]
                </a> |
                <a class="delete"
                   asp-action="Delete"
                   asp-controller="Questions"
                   asp-route-id="@item.Id"
                   asp-route-testId="@item.TestId">
                    @SharedLocalizer["Delete"]
                </a>
            </td>
        </tr>
    }
    </tbody>
</table>

<p>
    <a class="btn btn-primary" asp-action="Submit" asp-route-testId="@Model.TestId">@SharedLocalizer["Submit"]</a>
    <a class="btn btn-default" asp-action="Save" asp-controller="TestManagement" asp-route-id="@Model.TestId">@SharedLocalizer["Back"]</a>
    <a class="btn btn-danger" asp-action="Cancel" asp-controller="TestManagement" asp-route-testId="@Model.TestId">@SharedLocalizer["Cancel"]</a>
</p>